//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_GTFS_realtime.BT4U {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.bt4u.org/", ConfigurationName="BT4U.BT4U_WebServiceSoap")]
    public interface BT4U_WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetScheduledRoutes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetScheduledRoutes(string stopCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetScheduledRoutes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetScheduledRoutesAsync(string stopCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetScheduledStopCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetScheduledStopCodes(string routeShortName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetScheduledStopCodes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetScheduledStopCodesAsync(string routeShortName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetScheduledStopNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetScheduledStopNames(string routeShortName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetScheduledStopNames", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetScheduledStopNamesAsync(string routeShortName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetArrivalAndDepartureTimesForTrip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetArrivalAndDepartureTimesForTrip(string tripID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetArrivalAndDepartureTimesForTrip", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetArrivalAndDepartureTimesForTripAsync(string tripID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetScheduledPatternPoints", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetScheduledPatternPoints(string patternName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetScheduledPatternPoints", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetScheduledPatternPointsAsync(string patternName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetCurrentBusInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetCurrentBusInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetCurrentBusInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentBusInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetCurrentRoutes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetCurrentRoutes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetCurrentRoutes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentRoutesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetNextDepartures", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetNextDepartures(string routeShortName, string stopCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bt4u.org/GetNextDepartures", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetNextDeparturesAsync(string routeShortName, string stopCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BT4U_WebServiceSoapChannel : BT_GTFS_realtime.BT4U.BT4U_WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BT4U_WebServiceSoapClient : System.ServiceModel.ClientBase<BT_GTFS_realtime.BT4U.BT4U_WebServiceSoap>, BT_GTFS_realtime.BT4U.BT4U_WebServiceSoap {
        
        public BT4U_WebServiceSoapClient() {
        }
        
        public BT4U_WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BT4U_WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BT4U_WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BT4U_WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode GetScheduledRoutes(string stopCode) {
            return base.Channel.GetScheduledRoutes(stopCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetScheduledRoutesAsync(string stopCode) {
            return base.Channel.GetScheduledRoutesAsync(stopCode);
        }
        
        public System.Xml.XmlNode GetScheduledStopCodes(string routeShortName) {
            return base.Channel.GetScheduledStopCodes(routeShortName);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetScheduledStopCodesAsync(string routeShortName) {
            return base.Channel.GetScheduledStopCodesAsync(routeShortName);
        }
        
        public System.Xml.XmlNode GetScheduledStopNames(string routeShortName) {
            return base.Channel.GetScheduledStopNames(routeShortName);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetScheduledStopNamesAsync(string routeShortName) {
            return base.Channel.GetScheduledStopNamesAsync(routeShortName);
        }
        
        public System.Xml.XmlNode GetArrivalAndDepartureTimesForTrip(string tripID) {
            return base.Channel.GetArrivalAndDepartureTimesForTrip(tripID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetArrivalAndDepartureTimesForTripAsync(string tripID) {
            return base.Channel.GetArrivalAndDepartureTimesForTripAsync(tripID);
        }
        
        public System.Xml.XmlNode GetScheduledPatternPoints(string patternName) {
            return base.Channel.GetScheduledPatternPoints(patternName);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetScheduledPatternPointsAsync(string patternName) {
            return base.Channel.GetScheduledPatternPointsAsync(patternName);
        }
        
        public System.Xml.XmlNode GetCurrentBusInfo() {
            return base.Channel.GetCurrentBusInfo();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentBusInfoAsync() {
            return base.Channel.GetCurrentBusInfoAsync();
        }
        
        public System.Xml.XmlNode GetCurrentRoutes() {
            return base.Channel.GetCurrentRoutes();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentRoutesAsync() {
            return base.Channel.GetCurrentRoutesAsync();
        }
        
        public System.Xml.XmlNode GetNextDepartures(string routeShortName, string stopCode) {
            return base.Channel.GetNextDepartures(routeShortName, stopCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetNextDeparturesAsync(string routeShortName, string stopCode) {
            return base.Channel.GetNextDeparturesAsync(routeShortName, stopCode);
        }
    }
}
